### ISSUE TITLE
Error: Unable to load Binary into memory

### ISSUE THREAD

**Issue by troner14** [GaryCraft/ptero-plutonium#1]
I would like to set up a t6 server and I get those errors

0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002

and after nothing this error jumps:
Unable to load binary into memory
Unable to load binary into memory
X to: 99 connection broken (explicit delete or server shutdown).

**Comment by GaryCraft** [comment]
Could you explain how to reproduce this error?

**Comment by troner14** [comment]
when I start the server I get that, I did not touch or the configuration and the error appears

**Comment by GaryCraft** [comment]
Please Update your T6 Egg to the latest version and Reinstall your server ( Make sure to delete the files ), which should solve the ``` Unable to load binary into memory``` error.

As for the messages starting in 0048, I would consider them normal behavior, for the time being, I think they are caused by Wine and I see no fix for now.

Your server should start normally even if those messages appear

**Comment by troner14** [comment]
I have installed the latest version and when I start the server I get these errors
0050: err: ole: StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050: err: ole: CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050: err: ole: apartment_get_local_server_stream Failed: 0x80004002
0048: err: ole: StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048: err: ole: CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048: err: ole: apartment_get_local_server_stream Failed: 0x80004002
0048: err: ole: start_rpcss Failed to open RpcSs service
and after a short time the server consumption gets very low and does not start and stays like this 

![image](https://user-images.githubusercontent.com/73949396/147746835-3efa97a9-3bbf-46ed-91e2-c62ae205ec38.png)

**Comment by troner14** [comment]
Thanks for your help it takes us a while to start but in the end it does not start, I have a question where I can put the name so that it appears in the list of servers?

**Comment by GaryCraft** [comment]
The name that appears in the list is one labeled as hostname at the time you created your key

**Comment by troner14** [comment]
thanks

**Comment by troner14** [comment]
hello good when I create a dedicated server for zombies the cfg files for the configuration of each map I do not create them and then the server does not start

for example this '' 'zm_classic_processing.cfg' '' is not anywhere and is necessary to play a map

**Comment by GaryCraft** [comment]
That's an issue that may need a discussion on the Plutonium Forum directly, as I do not have the answer to that.
All the files provided by this egg are the ones gotten directly from them.
[T6 Hosting Support](https://forum.plutonium.pw/compose?cid=10)
I would actually want to know if those files can be put in the Egg by default.

**Comment by GaryCraft** [comment]
@troner14 The latest version of the T6 Egg does include those files before mentioned, however take care migrating to it, as this egg contains breaking changes
