### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by augesrob** [GaryCraft/ptero-plutonium#15]
**Is there away to use GSC to compile scripts**
This is used for adding mods.

Was thinking of adding 
https://pterodactylmarket.com/resource/143

This way it can be somewhat automated.

**Comment by GaryCraft** [comment]
There is currently no way to compile GSC scripts directly in the server, and Plutonium documentation refers to compiling GSC manually only.

The Resource you have linked to is a resource targeted towards the Pterodactyl Panel Itself and I do not have any way of testing it myself, but from what I can see, you would probably still have to upload the scripts pre-compiled.
