### ISSUE TITLE
SERVER NOT STARTING UP

### ISSUE THREAD

**Issue by navin-hariharan** [GaryCraft/ptero-plutonium#17]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from garycraft/ptero-plutonium 
Status: Image is up to date for ghcr.io/garycraft/ptero-plutonium:latest 
Digest: sha256:c90d6bb50c657a6ba71be3dd9030b8fa40cbd20c6412a980431bf727add2f7cd 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
exec /bin/bash: exec format error

**Comment by navin-hariharan** [comment]
https://vault.our-space.xyz/ATOM/T6-Server.zip

This URL is broken

Should I use this? https://codeload.github.com/xerxes-at/T6ServerConfigs/zip/refs/heads/master

**Comment by navin-hariharan** [comment]
![image](https://user-images.githubusercontent.com/42506955/174480837-3687c8d0-6941-4259-acfd-c0b00390c2e0.png)
This is my processor

**Comment by PilaScat** [comment]
same problem here, I'm trying deleting and reinstalling

**Comment by PilaScat** [comment]
Now it works, try that

**Comment by navin-hariharan** [comment]
Still the same buddy

> Now it works, try that

**Comment by navin-hariharan** [comment]
Are you using a ARM cpu or?

**Comment by navin-hariharan** [comment]
> Now it works, try that

What CPU do you use?

**Comment by PilaScat** [comment]
i7-2600k

**Comment by navin-hariharan** [comment]
> i7-2600k

I see that may be the problem! I'm using an Ampere CPU! It is a ARM-based processor

**Comment by PilaScat** [comment]
> > i7-2600k
> 
> I see that may be the problem! I'm using an Ampere CPU! It is a ARM-based processor

probably, I dunno

**Comment by GaryCraft** [comment]
https://github.com/GaryCraft/ptero-plutonium/issues/14#issuecomment-1104476681

This repository does not support ARM yet, as I said before, as long as Plutonium or Wine are not able to run in ARM, I cannot do much, the images available in this repo took some time to figure out, and actually, I did try to make them available for ARM too, unfortunately, Plutonium and Wine will not run in ARM.
