### ISSUE TITLE
server stuck on Loading fastfile seasonpass_load_zm

### ISSUE THREAD

**Issue by Megapluto8** [GaryCraft/ptero-plutonium#19]
hi i tryed to make a plutonium to6 zombies server but it keeps getting stuck at: Loading fastfile seasonpass_load_zm
is there a know fix for this?

**Comment by Dali1305** [comment]
same

**Comment by GaryCraft** [comment]
This is a problem not with the egg but directly with plutonium, this may be useful
[Plutonium Forum](https://forum.plutonium.pw/topic/16141/server-stuck-on-launch/11)
