### ISSUE TITLE
Zombies BO2

### ISSUE THREAD

**Issue by ByKoan** [GaryCraft/ptero-plutonium#2]
Hi! 
The egg been with-out the files necesseris to create it, how can i get it?

**Comment by GaryCraft** [comment]
Which Files Are Missing?

**Comment by ByKoan** [comment]
Al the cfg,s files of the maps, it have a solution or something?

**Comment by ByKoan** [comment]
![image](https://user-images.githubusercontent.com/70034019/149657933-5eca39b8-d046-4b17-85ff-47df5172c51f.png)
Thats its what i mean

**Comment by GaryCraft** [comment]
The temporal solution would be to upload them manually, later I will check if its possible to include them with the installation

**Comment by ByKoan** [comment]
so where can i find this files?

**Comment by GaryCraft** [comment]
you can probably find them here https://plutonium.pw/docs/install/#installing-the-base-game-bo2

**Comment by ByKoan** [comment]
okay, anyway if you find a solution pls tell me

**Comment by ByKoan** [comment]
hi again, i found the cfg's files required to the zombies but i dont have idea to configure it, i will try later but if you can add me on discord and help me, here is my user - Koan#0248
