### ISSUE TITLE
How to update to the recent plutonium version?

### ISSUE THREAD

**Issue by xMonologue** [GaryCraft/ptero-plutonium#22]
**Make your Question**
Hello I do not know how to update to the recent plutonium version, I tried reinstalling the server but since the new update of this week I cannot update it. When do you plan to add iw4m as an egg too? Thank you really much for your help!

**Comment by xMonologue** [comment]
![Uploading plutonium-bootstrapper-win32_3me6pq57aH.png…]()

**Comment by xMonologue** [comment]
Nvm found my issue my retarded ass didn't update the client on my KVM. Still wondering when you will launch the iw4m egg tho I really need it

**Comment by GaryCraft** [comment]
I'm glad you found the solution to your problem updates are automatic
If you are talking about IW4MAdmin I will probably be developing it soon.

**Comment by xMonologue** [comment]
> I'm glad you found the solution to your problem updates are automatic If you are talking about IW4MAdmin I will probably be developing it soon.

hey thanks for the answer, and if you do this thank you!
