### ISSUE TITLE
No zombies spawning in Nuketown - Can anyone reproduce?

### ISSUE THREAD

**Issue by Skwll** [GaryCraft/ptero-plutonium#23]
**Describe the bug**
Zombies are not spawning when starting a T6ZM Server with the map set to `exec zm_standard_nuked.cfg map zm_nuked` (Nuketown)
Therefore, the round will not start.
Can anyone reproduce this bug? I tried it on a fresh installation as well.

**To Reproduce**
1. Set the `sv_maprotation` in dedicated_zm.cfg to `sv_maprotation "exec zm_standard_nuked.cfg map zm_nuked"`

**Expected behavior**
Zombies should start spawning as soon as you join.

**Additional Information**
I've also tried changing the resource limits of the pterodactyl server to unlimited in case the server would enter some kind of lock state and therefore stopping to spawn entities, but it did not help.

**Comment by GaryCraft** [comment]
Please check if this issue is only happening when using ptero-plutonium or has been documented elsewhere, I'd recommend checking [Plutonium's T6 Forum](https://forum.plutonium.pw/category/10/bo2-server-hosting-support)

**Comment by Skwll** [comment]
> Please check if this issue is only happening when using ptero-plutonium or has been documented elsewhere, I'd recommend checking [Plutonium's T6 Forum](https://forum.plutonium.pw/category/10/bo2-server-hosting-support)

Yes, this is only happening when using ptero-plutonium.

**Comment by Skwll** [comment]
I was able to resolve this by adding the missing config files from plutonium in `/Server/Zombie/t6r/data/gamesettings/`
