### ISSUE TITLE
repeat heartbeats?

### ISSUE THREAD

**Issue by ghost** [GaryCraft/ptero-plutonium#26]
Repeat heartbeats?
Loading fastfile mp_la
Loading fastfile faction_fbi_mp
Loading fastfile faction_pmc_mp
Sending heartbeat...
Heartbeat successful.
Sending heartbeat...
Heartbeat successful.
Sending heartbeat...
Heartbeat successful.
Sending heartbeat...
Heartbeat successful.
Sending heartbeat...
Heartbeat successful.

cannot connect...

**Comment by GaryCraft** [comment]
This is not a bug, it is how a heartbeat works, please add your log between 
\`\`\`
\`\`\`
symbols so I can Identify what is the log and what is your question
