### ISSUE TITLE
Cannot connect to Server

### ISSUE THREAD

**Issue by 3deeee** [GaryCraft/ptero-plutonium#27]
Hi Gary,

first of all, thank you very much for creating this egg! I'm very thankful and I even installed Pterodactyl on my unRAID System, just for this egg :-)

**Describe the bug**
The Server starts up fine, but it is not connectable.

**To Reproduce**
1. Follow the installation steps
2. Install and start the server

**Expected behavior**
I expect my game to be able to connect to the server.

**Screenshots**
![image](https://github.com/GaryCraft/ptero-plutonium/assets/81199908/540c6e15-ab9e-4caf-9789-dcc8474166cc)

**Additional Information**
I made sure that I don't have any firewall issues. Since I'm trying to connect to the server via it's local IP, port forwarding in the router is not the problem, although port forwarding is already set up correctly.

To make sure it's not a problem with my Pterodactyl installation, I installed a Minecraft Server on Port 28016.

I can connect to the Minecraft Server perfectly on 192.168.1.10:28016

I cannot connect to the Plutonium Server on 192.168.1.10:28015

I verified both with telnet:

cmd connects: telnet 192.168.1.10 28016
cmd cannot connect: telnet 192.168.1.10 28015

The Server keeps sending a heartbeat and I don't see any errors in the console.

Startup command is:

Running bin/plutonium-bootstrapper-win32.exe t6mp /home/container/Server/Multiplayer/ -dedicated +start_map_rotate +set key myprivateserverkey +set net_port 28015 +set sv_config dedicated.cfg

There are no firewalls on my unRAID System.

Let me know if I can get you any logs or further information.

Thanks!!

**Comment by GaryCraft** [comment]
I know you said there isn't any firewall, just check that you can use UDP connections, telnet can only test TCP, you can check this by using netcat, also remember that pterodactyl uses docker, and as so you may need to connect to its network, check in your system for the pterodactyl0 interface (usually bound to 172.18.0.1)

**Comment by GaryCraft** [comment]
if assistance is still needed for this issue please contact me via direct message in discord
