### ISSUE TITLE
Cannot play at Tranzit map in survival mode (town,farm,bus depot...)

### ISSUE THREAD

**Issue by bartoggy** [GaryCraft/ptero-plutonium#28]
**Describe the bug**
Hello,

When a set map as town farm ... the gamode is everytime tranzit and not survival and i spawn on bus depot

My map config :

//Custom 
sv_maprotation "exec zm_standard_farm.cfg map zm_transit"

**To Reproduce**
just change map config like mine

**Expected behavior**
start the map farm as survival and not the tranzit gamemode and map

thanks in advance

**Comment by AhmedBonnah** [comment]
any fix ? , after reinstalling it doesnt load in any map now

**Comment by GaryCraft** [comment]
This does not seem to be an issue with the egg itself thus not fixable in this repo, however you might be able to fix it solely changing the contents of the configuration files

Also search in the plutonium forum about the same issue, as there you might find someone who has already found a solution to your problem
[Plutonium Forum](https://forum.plutonium.pw/category/10/bo2-server-hosting-support)
