### ISSUE TITLE
IW4Admin Requires access to Plutonium logs

### ISSUE THREAD

**Issue by 0x3770** [GaryCraft/ptero-plutonium#5]
when connected IW4MAdmin to my server it seems to be trying to connect but can't reach /home/container/Plutonium/storage/t6/logs/games_mp.log

but looking in Pterodactyl the file does indeed exist but can't find it

any suggestions maybe its a docker thing I don't understand

**Comment by GaryCraft** [comment]
Have you tried yet adding 2 Network ports?
One for Plutonium and one for Plutonium's RCON

If not done like that the issue may just be that

This is needed as docker isolates the incoming network connections to each container/server and adding a second port also opens up the firewall, this also means that when a connection reaches the host, it can be redirected to the matching container.


So just add 2 Network ports and use one for the server and the other for RCON

**Comment by 0x3770** [comment]
did some looking about and I'm a bit confused
I'm running the actual game server on the default 4976 and I can access it on the game perfectly fine 
In the IW4MAdmin configuration I believe it asks for the same port as the game is running on 4976? 

little confused about the second port / how to add it / what it should be
where would it be configured pterodactyl or game cfg files or does the port simply just have to be there

EDIT: having more issues I believe not to be related to this project, so might not respond for a bit. every time I make progress more issues pop up, Tech am i right? lol

**Comment by GaryCraft** [comment]
I've done some research now, and to add IW4Admin some modifications need to be made to the current setup, as IW4Admin needs access to local logs or remote logs from your server, and that can't be done from the same container, yet.
