### ISSUE TITLE
This server is out of date! Server version: 2234 Latest version: 2748

### ISSUE THREAD

**Issue by mga-py** [GaryCraft/ptero-plutonium#6]
Could you indicate how to update the version, the current version says that it is old and I think that is why the server does not work in my game

This server is out of date!
Server version: 2234
Latest version: 2748

**Comment by mga-py** [comment]
I managed to create a package with the plutonium upgradeables here the package http://tdcommunity.sytes.net:8081/T6-Server.zip but now I find that it returns this error

Sending heartbeat...
Could not send heartbeat to nix! Error was: context: error retrieving entropy
connection with nix socket lost, reconnecting in 15s...
Sending heartbeat...
Could not send heartbeat to nix! Error was: context: error retrieving entropy
connection with nix socket lost, reconnecting in 15s...

I do not understand very well why it is produced, apparently the key is in its place and everything,
try to put in the container

apt-get install haveged -y

systemctl enable haveged && systemctl start haveged

as indicated here https://forum.plutonium.pw/topic/901/linux-ubuntu-heartbeat-errors?_=1644024525704

but nothing remains the same, please help me I am very interested in this topic, it is true that the only thing that I do not have external vision is by dns because by the public IP of the router I do go perfectly and I have my router and everything correctly configured in fact in the old version in the plutoniom api appeared but only with an old version the same when updating you have to take into account some file

**Comment by GaryCraft** [comment]
This repository does not actually manage the files needed to run the server itself, After installing the egg on the panel, and creating a server, you will see an option to input a download URL for your server. This will be used by the egg to download and install your Plutonium server, one that you could use https://dl.axite.dev/T6-Server.zip .

This repo only manages the image that pterodactyl/wings uses to run it, and the egg that contains the installation script and the image

But, the server does have a default download link that most times has to be replaced, it is fully capable of running both Zombies and Multiplayer, but sometimes it's not updated to the latest version, cause I update it manually.
