### ISSUE TITLE
Will wine be updated?

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [GaryCraft/ptero-plutonium#7]
This is not a bug concern but more of a question if you're going to update wine to the latest version?

**Comment by GaryCraft** [comment]
As a very short answer, yes.

As for the slightly shorter answer, I will have to test a while to see if no problems arise from updating, also if there is any compelling reason to do so.

**Comment by ZEROPOINTBRUH** [comment]
if you need a server to test it on i'd be more then happy to negotiate on discord. (hit me up @zeropoint#9798)
