### ISSUE TITLE
connection with nix socket lost, reconnecting in 15s...

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [GaryCraft/ptero-plutonium#8]
wine-6.0.1
Running bin/plutonium-bootstrapper-win32.exe t6mp /home/container/Server/Multiplayer/ -dedicated +start_map_rotate +set key CXyJqEAkaZ4K3WDPZnF4uDFf4akmPWQv +set net_port 62260 +set sv_config dedicated.cfg
0048:err:ole:start_rpcss Failed to open RpcSs service
[WARNING] could not initialize curses! falling back to stdout.
connection with nix socket lost, reconnecting in 15s...
Loading fastfile code_pre_gfx_mp
0024:err:ole:com_get_class_object class {e436ebb3-524f-11ce-9f53-0020af0ba770} not registered
0024:err:ole:com_get_class_object no class object {e436ebb3-524f-11ce-9f53-0020af0ba770} could be created for context 0x1
[STEAM] 1 calls ready, running...
[STEAM] running call 1
[DW][Auth] Handling authentication request...
Loading fastfile patch_mp
Loading fastfile code_post_gfx_mp
Parsing menu ui/t6/menus/optionscontrols.lua...
Parsing menu ui/t6/menus/optionssettings.lua...
Parsing menu ui/t6/dvarleftrightselector.lua...
Parsing menu ui/t6/menus/safeareamenu.lua...
Parsing menu ui_mp/t6/mainmenu.lua...
Parsing menu ui_mp/t6/hud/loading.lua...
Parsing menu ui_mp/t6/hud/scoreboard.lua...
Parsing menu ui_mp/t6/hud/spectateplayercard.lua...
Parsing menu ui_mp/t6/hud/class.lua...
Parsing menu ui_mp/t6/hud/team_marinesopfor.lua...
[DW][Lobby] Handling hello request...
Setting net_port to "62260" from command line.
bound socket to localhost:62260
config file %s not found.
Loading fastfile patch_ui_mp
Loading fastfile ui_mp
Parsing menu ui/t6/mainlobby.lua...
Parsing menu ui/t6/partylobby.lua...
Parsing menu ui/t6/menus/partyprivacypopup.lua...
Parsing menu ui/t6/menus/privategamelobby.lua...
Parsing menu ui_mp/t6/menus/privategamelobby_project.lua...
Parsing menu ui_mp/t6/menus/theaterlobby.lua...
Loading fastfile ffotd_tu13_mp_147
Loading fastfile common_mp
Loading fastfile common_patch_mp
scanning for plugins...
Loading fastfile dlc0_load_mp
Loading fastfile dlc1_load_mp
Loading fastfile dlc2_load_mp
Loading fastfile dlc3_load_mp
Loading fastfile dlc4_load_mp
Loading fastfile dlc0dd_load_mp
Loading fastfile seasonpass_load_mp
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...
connection with nix socket lost, reconnecting in 15s...

**Comment by GaryCraft** [comment]
I would recommend researching the error in the [Plutonium Forum](https://forum.plutonium.pw/category/10/bo2-server-hosting-support ), as it is a plutonium error and not the image's or egg's.
If a fix is needed to the egg or image, that will be addressed here.

A small search turns me to an error in configuration, make sure that you have put your key correctly in the server's startup settings.

**Comment by ZEROPOINTBRUH** [comment]
I think I've noticed what's going on within the server and the issue of why the servers not getting a stable connection. The server requires a UPnP port to allocate to when running the server when the server tries to make that call. The server doesn't see the server connection going through.

**Comment by GaryCraft** [comment]
That happens automatically, no UPnP needed, you can see it allocating a port in the startup configuration

**Comment by GaryCraft** [comment]
@ZEROPOINTBRUH check that you have put your key from plutonium on the Startup settings correctly
